
CREATE TABLE USERS
(
  USER_UID      VARCHAR(100) NOT NULL COMMENT '사용자 아이디',
  NAME          VARCHAR(100) NOT NULL COMMENT '사용자 이름',
  PASSWORD      VARCHAR(100) NOT NULL COMMENT '사용자 비밀번호',
  E_MAIL        VARCHAR(100) NULL     COMMENT '사용자 이메일',
  POSTCODE      VARCHAR(100) NOT NULL COMMENT '우편번호',
  ADDRESS       VARCHAR(100) NOT NULL COMMENT '주소',
  ADDRESSDETAIL VARCHAR(100) NOT NULL COMMENT '상세주소',
  JOINDATE      DATETIME     NOT NULL COMMENT '가입일',
  PHONE         INTEGER(20)  NULL     COMMENT '전화번호',
  GRADE         VARCHAR(100) NOT NULL COMMENT '사용자 등급',
  USER_AUTH     VARCHAR(100) NOT NULL COMMENT '사용자 권한',
  PRIMARY KEY (USER_UID)
) COMMENT '사용자들';
