
CREATE TABLE BOARD
(
  BOARD_UID       VARCHAR(100) NOT NULL COMMENT '게시글UID',
  BOARD_TITLE     VARCHAR(100) NOT NULL COMMENT '게시글 제목',
  BOARD_TYPE      VARCHAR(100) NOT NULL COMMENT '게시판 분류',
  BOARD_CONTENT   VARCHAR(100) NULL     COMMENT '게시글 내용',
  BOARD_FILE_NAME VARCHAR(100) NULL     COMMENT '파일 이름',
  BOARD_DATE      DATETIME     NOT NULL COMMENT '게시글 등록일',
  PRIMARY KEY (BOARD_UID)
) COMMENT '게시판';
