
CREATE TABLE EVENT_BOARD
(
  EVENT_UID    VARCHAR(100) NOT NULL COMMENT '이벤트UID',
  EVENT_PERIOD DATETIME     NULL     COMMENT '이벤트 기간',
  TITLE        VARCHAR(100) NOT NULL COMMENT '제목',
  CONTENT      VARCHAR(100) NULL     COMMENT '내용',
  DATE_CREATED DATETIME     NOT NULL COMMENT '작성일',
  WRITER       VARCHAR(100) NOT NULL COMMENT '작성자',
  PRIMARY KEY (EVENT_UID)
) COMMENT '이벤트게시판';
