
CREATE TABLE FAQ
(
  FAQ_UID  VARCHAR(100) NOT NULL COMMENT '질문답변UID',
  TITLE    VARCHAR(100) NOT NULL COMMENT '제목',
  CONTENT  VARCHAR(500) NOT NULL COMMENT '내용',
  FAQ_TYPE VARCHAR(100) NOT NULL COMMENT '문의종류',
  PRIMARY KEY (FAQ_UID)
) COMMENT '질문답변';
