
CREATE TABLE INQUIRY_LIST
(
  INQUIRY_LIST_UID VARCHAR(100) NOT NULL COMMENT '1:1문의 목록UID',
  INQUERY_TITLE    VARCHAR(100) NOT NULL COMMENT '문의제목',
  INQUERY_DATE     DATETIME     NOT NULL COMMENT '문의날짜',
  INQUIRY_TYPE     VARCHAR(100) NOT NULL COMMENT '문의유형',
  SLEDDING         VARCHAR(100) NOT NULL COMMENT '진행상태',
  PRIMARY KEY (INQUIRY_LIST_UID)
) COMMENT '1:1문의 목록';
