
CREATE TABLE INQUIRY_VIEW
(
  INQUIRY_VIEW_UID VARCHAR(100) NOT NULL COMMENT '1:1문의 상세UID',
  INQUERY_TITLE    VARCHAR(100) NOT NULL COMMENT '문의제목',
  INQUERY_DATE     DATETIME     NOT NULL COMMENT '문의날짜',
  INQUIRY_CONTENT  VARCHAR(100) NOT NULL COMMENT '문의내용',
  INQUIRY_TYPE     VARCHAR(100) NOT NULL COMMENT '문의유형',
  PRIMARY KEY (INQUIRY_VIEW_UID)
) COMMENT '1:1문의 상세';
