-- adminInquiry
-- NAME, USER_UID, INQUIRY_TITLE, INQUIRY_DATE, INQUIRY_CONTENT, INQUIRY_ANSWER, INQUIRY_TYPE
-- 사용자 이름, 사용자 아이디, 문의제목, 문의날짜, 문의내용, 1:1문의 답변, 문의유형
SELECT USERS.NAME, USERS.USER_UID, INQUIRY_TYPES.INQUIRY_TYPE, INQUIRYS.INQUIRY_TITLE, INQUIRYS.INQUIRY_DATE, INQUIRYS.INQUIRY_CONTENT, 
		INQUIRYS.INQUIRY_ANSWER
FROM INQUIRY_TYPES INNER JOIN INQUIRYS 
ON INQUIRY_TYPES.INQUIRY_TYPE_UID=INQUIRYS.INQUIRY_TYPE_UID
INNER JOIN USERS
ON INQUIRYS.USER_UID=USERS.USER_UID;

