-- adminBoard
-- TITLE, DATE_CREATED, BOARD_TYPE_DESCRIPTION
-- 게시글 제목, 작성일, 게시판 분류 설명
SELECT COMMON_BOARD.TITLE, COMMON_BOARD.DATE_CREATED, MAIN_BOARD.BOARD_TYPE_DESCRIPTION
FROM MAIN_BOARD INNER JOIN COMMON_BOARD
ON MAIN_BOARD.BOARD_UID = COMMON_BOARD.BOARD_UID;

-- adminBoardCreate, adminBoardUpdate
-- TITLE, CONTENT, BOARD_TYPE_DESCRIPTION, BOARD_FILE_NAME
-- 게시글 제목, 게시글 내용, 게시판 분류 설명, 게시글 파일 명
SELECT COMMON_BOARD.TITLE, COMMON_BOARD.CONTENT, COMMON_BOARD.BOARD_FILE_NAME, MAIN_BOARD.BOARD_TYPE_DESCRIPTION
FROM MAIN_BOARD INNER JOIN COMMON_BOARD
ON MAIN_BOARD.BOARD_UID = COMMON_BOARD.BOARD_UID;

-- adminInquiry
-- NAME, USER_UID, INQUIRY_TITLE, INQUIRY_DATE, INQUIRY_CONTENT, INQUIRY_ANSWER, INQUIRY_TYPE
-- 사용자 이름, 사용자 아이디, 문의제목, 문의날짜, 문의내용, 1:1문의 답변, 문의유형
SELECT USERS.NAME, USERS.USER_UID, INQUIRY_TYPES.INQUIRY_TYPE, INQUIRYS.INQUIRY_TITLE, INQUIRYS.INQUIRY_DATE, INQUIRYS.INQUIRY_CONTENT, 
		INQUIRYS.INQUIRY_ANSWER
FROM INQUIRY_TYPES INNER JOIN INQUIRYS 
ON INQUIRY_TYPES.INQUIRY_TYPE_UID = INQUIRYS.INQUIRY_TYPE_UID
INNER JOIN USERS
ON INQUIRYS.USER_UID = USERS.USER_UID;

-- adminUsers
-- NAME, USER_UID, JOINDATE, BIRTH_DATE, PHONE, E_MAIL, ADDRESS, DETAILADDRESS, EXTRAADDRESS, GRADE
-- 사용자 이름, 사용자 아이디, 가입일, 전화번호, 사용자 이메일, 주소, 상세주소, 주소참고사항, 등급
SELECT USERS.NAME, USERS.USER_UID, USERS.JOINDATE, USERS.BIRTH_DATE, USERS.PHONE, USERS.E_MAIL, USERS.ADDRESS,
		USERS.DETAILADDRESS, USERS.EXTRAADDRESS, USER_GRADES.GRADE
FROM USER_GRADES INNER JOIN USERS
ON USERS.GRADE_UID = USER_GRADES.GRADE_UID;

-- adminUserCreate, adminUserUpdate
-- NAME, USER_UID, PASSWORD, BIRTH_DATE, GRADE, E_MAIL, PHONE, POSTALCODE, ADDRESS, DETAILADDRESS, EXTRAADDRESS
-- 사용자 이름, 사용자 아이디, 사용자 비밀번호, 생년월일, 등급, 사용자 이메일, 전화번호, 우편번호, 주소, 상세주소, 주소참고사항
SELECT USERS.NAME, USERS.USER_UID, USERS.PASSWORD, USERS.BIRTH_DATE, USERS.PHONE, USERS.POSTALCODE, USERS.E_MAIL, USERS.ADDRESS,
		USERS.DETAILADDRESS, USERS.EXTRAADDRESS, USER_GRADES.GRADE
FROM USER_GRADES INNER JOIN USERS
ON USERS.GRADE_UID = USER_GRADES.GRADE_UID;

-- eventList
-- TITLE, CONTENT, DATE_CREATED, BOARD_FILE_NAME, EVENT_START_DATE, EVENT_END_DATE
-- 게시글 제목, 게시글 내용, 작성일, 게시글 파일 명, 이벤트 시작 일, 이벤트 끝일
SELECT TITLE, CONTENT, DATE_CREATED, BOARD_FILE_NAME, EVENT_START_DATE, EVENT_END_DATE
FROM COMMON_BOARD INNER JOIN MAIN_BOARD
ON COMMON_BOARD.BOARD_UID = MAIN_BOARD.BOARD_UID
AND MAIN_BOARD.BOARD_TYPE = 'EVENT';

-- eventView
-- TITLE, CONTENT, DATE_CREATED, BOARD_FILE_NAME, EVENT_START_DATE, EVENT_END_DATE
-- 게시글 제목, 게시글 내용, 작성일, 게시글 파일 명, 이벤트 시작 일, 이벤트 끝일
SELECT TITLE, CONTENT, DATE_CREATED, BOARD_FILE_NAME, EVENT_START_DATE, EVENT_END_DATE
FROM COMMON_BOARD;

-- IdResult_su
-- USER_UID
-- 사용자 아이디
SELECT USER_UID
FROM USERS;

-- IdSearch
-- NAME, PHONE
-- 사용자 이름, 전화번호
SELECT NAME, PHONE
FROM USERS;

-- index
-- NAME, USER_UID, GRADE, POINT, BOARD_FILE_NAME, TITLE, DATE_CREATED
-- 사용자 이름, 사용자 아이디, 등급, 포인트, 게시글 제목, 작성일
SELECT USERS.NAME, USERS.USER_UID, USER_GRADES.GRADE, USERS.POINT, COMMON_BOARD.BOARD_FILE_NAME,
		COMMON_BOARD.TITLE, COMMON_BOARD.DATE_CREATED
FROM USER_GRADES INNER JOIN USERS
ON USER_GRADES.GRADE_UID = USERS.GRADE_UID
INNER JOIN COMMON_BOARD
ON USERS.USER_UID = COMMON_BOARD.USER_UID;

-- inquiryList
-- INQUIRY_TITLE, INQUIRY_DATE, INQUIRY_TYPE_DESCRIPTION, PROGRESS_STATUS_DESCRIPTION
-- 문의제목, 문의날짜, 문의유형 설명, 진행상태설명
SELECT INQUIRYS.INQUIRY_TITLE, INQUIRYS.INQUIRY_DATE, INQUIRY_TYPES.INQUIRY_TYPE_DESCRIPTION,
		PROGRESS_STATUS_TYPE.PROGRESS_STATUS_DESCRIPTION
FROM PROGRESS_STATUS_TYPE INNER JOIN INQUIRYS
ON PROGRESS_STATUS_TYPE.PROGRESS_STATUS_UID = INQUIRYS.PROGRESS_STATUS_UID
INNER JOIN INQUIRY_TYPES
ON INQUIRYS.INQUIRY_TYPE_UID = INQUIRY_TYPES.INQUIRY_TYPE_UID;

-- inquiryView
-- INQUIRY_TITLE, INQUIRY_DATE, INQUIRY_CONTENT, INQUIRY_TYPE_DESCRIPTION
-- 문의제목, 문의날짜, 문의내용, 문의유형 설명
SELECT INQUIRYS.INQUIRY_TITLE, INQUIRYS.INQUIRY_DATE, INQUIRYS.INQUIRY_CONTENT, INQUIRY_TYPES.INQUIRY_TYPE_DESCRIPTION
FROM INQUIRY_TYPES INNER JOIN INQUIRYS
ON INQUIRY_TYPES.INQUIRY_TYPE_UID = INQUIRYS.INQUIRY_TYPE_UID;

-- join_step1
-- MARKETING_RECEIVE_ACCEPTION ?
-- 선택 양관 동의
SELECT MARKETING_RECEIVE_ACCEPTION
FROM USERS;

-- join_step2
-- NAME, USER_UID, PASSWORD
-- 사용자 이름, 사용자 아이디, 사용자 비밀번호
SELECT NAME, USER_UID, PASSWORD
FROM USERS;

-- join_step3
-- PHONE, E_MAIL, POSTALCODE, ADDRESS, DETAILADDRESS, EXTRAADDRESS
-- 전화번호, 사용자 이메일, 우편번호, 주소, 상세주소, 주소참고사항
SELECT PHONE, E_MAIL, POSTALCODE, ADDRESS, DETAILADDRESS, EXTRAADDRESS
FROM USERS;

-- join_step4
-- BIRTH_DATE, NAME, PHONE, ADDRESS, DETAILADDRESS, EXTRAADDRESS, E_MAIL, USER_UID
-- 생년월일, 사용자 이름, 전화번호, 주소, 상세주소, 주소참고사항, 사용자 이메일, 사용자 아이디
SELECT BIRTH_DATE, NAME, PHONE, ADDRESS, DETAILADDRESS, EXTRAADDRESS, E_MAIL, USER_UID
FROM USERS;

-- login
-- USER_UID, PASSWORD
-- 사용자 아이디, 사용자 비밀번호
SELECT USER_UID, PASSWORD
FROM USERS;

-- memberInquiry
-- NAME, E_MAIL, PHONE, INQUIRY_TYPE_DESCRIPTION, TRACKING_NUMBER_FOR_INQUIRY, INQUIRY_TITLE, INQUIRY_CONTENT
-- 사용자 이름, 사용자 이메일, 전화번호, 문의유형 설명, 1:1 문의용 운송장번호, 문의제목, 문의내용
SELECT USERS.NAME, USERS.E_MAIL, USERS.PHONE, INQUIRY_TYPES.INQUIRY_TYPE_DESCRIPTION, INQUIRYS.INQUIRY_TITLE,
		INQUIRYS.INQUIRY_CONTENT
FROM INQUIRY_TYPES INNER JOIN INQUIRYS
ON INQUIRY_TYPES.INQUIRY_TYPE_UID = INQUIRYS.INQUIRY_TYPE_UID
INNER JOIN USERS
ON INQUIRYS.USER_UID = USERS.USER_UID;

-- myinfo
-- NAME, BIRTH_DATE, PASSWORD, PHONE, POSTALCODE, ADDRESS, DETAILADDRESS, EXTRAADDRESS
-- 사용자 이름, 생년월일, 사용자 비밀번호, 전화번호, 우편번호, 주소, 상세주소, 주소참고사항
SELECT NAME, BIRTH_DATE, PASSWORD, PHONE, POSTALCODE, ADDRESS, DETAILADDRESS, EXTRAADDRESS
FROM USERS;

-- myinfoPass
-- PASSWORD
SELECT PASSWORD
FROM USERS;

-- mypage
-- NAME, GRADE, POINT, SHIPMENT_TYPE_DESCRIPTION, RESERVATION_DATE, SHIPMENT_COMPLETION_DATE, RECIPIENT_PHONE,
-- RECIPIENT_NAME, DESTINATION_ADDRESS, DESTINATION_DETAILADDRESS, DESTINATION_EXTRAADDRESS
-- 사용자 이름, 등급, 포인트, 배송타입 설명, 예약날짜, 배송완료일자, 수령자 전화번호, 수령자 이름, 목적지 주소, 목적지 상세주소, 목적지 주소 참고사항
SELECT USERS.NAME, USER_GRADES.GRADE, USERS.POINT, SHIPMENT_TYPES.SHIPMENT_TYPE_DESCRIPTION,
		SHIPMENT.RESERVATION_DATE, SHIPMENT.SHIPMENT_COMPLETION_DATE, SHIPMENT.RECIPIENT_PHONE, SHIPMENT.RECIPIENT_NAME,
        SHIPMENT.DESTINATION_ADDRESS, SHIPMENT.DESTINATION_DETAILADDRESS, SHIPMENT.DESTINATION_EXTRAADDRESS
FROM USER_GRADES INNER JOIN USERS
ON USER_GRADES.GRADE_UID = USERS.GRADE_UID
INNER JOIN MYPAGE
ON USERS.USER_UID = MYPAGE.USER_UID
INNER JOIN SHIPMENT
ON MYPAGE.TRACKING_NUMBER = SHIPMENT.TRACKING_NUMBER
INNER JOIN SHIPMENT_TYPES
ON SHIPMENT.SHIPMENT_TYPE_UID = SHIPMENT_TYPES.SHIPMENT_TYPE_UID;

-- noticeList
-- TITLE, DATE_CREATED
-- 게시글 제목, 작성일
SELECT COUNT(*) AS 'TOTAL', TITLE, DATE_CREATED
FROM COMMON_BOARD INNER JOIN MAIN_BOARD
ON COMMON_BOARD.BOARD_UID = MAIN_BOARD.BOARD_UID
AND MAIN_BOARD.BOARD_TYPE = 'NOTICE';

-- 공지사항 페이지네이션인데 머가 안됨. 다시 봐야함
-- 이거 되면 이벤트리스트에도 페이지네이션 추가하기
SELECT *
FROM COMMON_BOARD INNER JOIN MAIN_BOARD
ON COMMON_BOARD.BOARD_UID = MAIN_BOARD.BOARD_UID
AND MAIN_BOARD.BOARD_TYPE = 'NOTICE'
order by COMMON_BOARD.COMMONBOARD_UID
LIMIT 1, 5;

-- noticeView
-- TITLE, DATE_CREATED, VIEWS, CONTENT, BOARD_FILE_NAME
-- 게시글 제목, 작성일, 조회수, 게시글 내용, 게시글 파일 명
SELECT TITLE, DATE_CREATED, VIEWS, CONTENT, BOARD_FILE_NAME
FROM COMMON_BOARD;