
CREATE TABLE INQUIRY
(
  INQUIRY_UID       VARCHAR(100) NOT NULL COMMENT '1:1문의UID',
  USER_NAME         VARCHAR(100) NOT NULL COMMENT '사용자이름',
  USER_EMAIL        VARCHAR(100) NOT NULL COMMENT '사용자이메일',
  USER_PHONE_NUMBER VARCHAR(100) NOT NULL COMMENT '사용자휴대폰번호',
  INQUIRY_TYPE      VARCHAR(100) NOT NULL COMMENT '문의유형',
                    INTEGER(100) NULL     COMMENT '운송장번호'
) COMMENT '1:1문의';
