
CREATE TABLE MYPAGE
(
  MYPAGE_UID    VARCHAR(100) NOT NULL COMMENT '마이페이지UID',
  USER_NAME     VARCHAR(100) NOT NULL COMMENT '사용자이름',
  USER_GRADE    VARCHAR(100) NOT NULL COMMENT '사용자등급',
  POINT         INTEGER      NOT NULL COMMENT '포인트',
  INQUIRY_COUNT INREGER      NOT NULL COMMENT '문의개수',
  PRIMARY KEY (MYPAGE_UID)
) COMMENT '마이페이지';
