
CREATE TABLE NOTICE_BOARD
(
  NOTICE_UID   VARCHAR(100) NOT NULL COMMENT '공지사항UID',
  TITLE        VARCHAR(100) NOT NULL     COMMENT '제목',
  CONTENT      VARCHAR(500) NULL     COMMENT '내용',
  DATE_CREATED DATETIME     NOT NULL     COMMENT '작성일',
  WRITER       VARCHAR(100) NOT NULL     COMMENT '작성자',
  VIEWS        INTEGER NOT NULL     COMMENT '조회수',
  BOARD_FILE_NAME VARCHAR(100) NULL     COMMENT '파일 이름'
  PRIMARY KEY (NOTICE_UID)
) COMMENT '공지사항 게시판';
