
CREATE TABLE NOTICE
(
  NOTICE_TITLE   VARCHAR(!00) NOT NULL COMMENT '공지사항 제목',
  NOTICE_DATE    DATETIME     NOT NULL COMMENT '공지사항 날짜',
  NOTICE_CONTENT VARCHAR(!00) NULL     COMMENT '공지사항 내용'
) COMMENT '공지사항';
