
CREATE TABLE SHIPPING_RESERVATION
(
  TRACKING_NUMBER           VARCHAR(100) NOT NULL COMMENT '운송장번호',
  ITEM_TYPE                 VARCHAR(100) NOT NULL COMMENT '물품종류',
  NUMBER_OF_ITEMS           INTEGER      NOT NULL COMMENT '총 발송 수량',
  SENDER_NAME               VARCHAR(100) NOT NULL COMMENT '발신자 이름',
  SENDER_PHONE              INTEGER      NOT NULL COMMENT '발신자 전화번호',
  DEPARTURE_POSTALCODE      INTEGER      NOT NULL COMMENT '출발지 우편번호',
  DEPARTURE_ADDRESS         VARCHAR(100) NOT NULL COMMENT '출발지 주소',
  DEPARTURE_ADDRESSDETAIL   VARCHAR(100) NOT NULL COMMENT '출발지 상세주소',
  RECIPIENT_NAME            VARCHAR(100) NOT NULL COMMENT '수령자 이름',
  RECIPIENT_PHONE           INTEGER      NOT NULL COMMENT '수령자 전화번호',
  DESTINATION_POSTALCODE    INTEGER      NOT NULL COMMENT '목적지 우편번호',
  DESTINATION_ADDRESS       VARCHAR(100) NOT NULL COMMENT '목적지 주소',
  DESTINATION_ADDRESSDETAIL VARCHAR(100) NOT NULL COMMENT '목적지 상세주소',
  REQUEST                   VARCHAR(100) NULL     COMMENT '요청사항',
  TOTAL_PRICE               INTEGER      NOT NULL COMMENT '총요금',
  ITEM_PRICE                INTEGER      NOT NULL COMMENT '물품단가',
  SHIPPING_PASSWORD         INTEGER      NOT NULL COMMENT '배송비밀번호',
  VISITING_DATE             DATETIME     NOT NULL COMMENT '방문희망일',
  PRIMARY KEY (TRACKING_NUMBER)
) COMMENT '배송예약';
