
CREATE TABLE COMMON_BOARD
(
  COMMONBOARD_UID  VARCHAR(100) NOT NULL COMMENT '게시글 UID',
  TITLE            VARCHAR(100) NOT NULL COMMENT '게시글 제목',
  CONTENT          VARCHAR(500) NULL     COMMENT '게시글 내용',
  DATE_CREATED     DATETIME     NOT NULL COMMENT '작성일',
  WRITER           VARCHAR(100) NOT NULL COMMENT '작성자',
  VIEWS            INTEGER      NOT NULL COMMENT '조회수',
  BOARD_FILE_NAME  VARCHAR(100) NULL     COMMENT '게시글 파일 명',
  EVENT_START_DATE DATETIME     NULL     COMMENT '이벤트 시작 일',
  EVENT_END_DATE   DATETIME     NULL     COMMENT '이벤트 끝일',
  USER_UID         VARCHAR(100) NOT NULL COMMENT '사용자 아이디',
  BOARD_UID        VARCHAR(100) NOT NULL COMMENT '게시글UID',
  PRIMARY KEY (COMMONBOARD_UID)
) COMMENT '전체 게시판';

CREATE TABLE MAIN_BOARD
(
  BOARD_UID         VARCHAR(100) NOT NULL COMMENT '게시글UID',
  BOARD_TYPE        VARCHAR(100) NOT NULL COMMENT '게시판 분류',
  BOARD_DESCRIPTION     VARCHAR(100)         NULL COMMENT '게시판설명'    ,
  PRIMARY KEY (BOARD_UID)
) COMMENT '게시판';

ALTER TABLE COMMON_BOARD
  ADD CONSTRAINT FK_MAIN_BOARD_TO_COMMON_BOARD
    FOREIGN KEY (BOARD_UID)
    REFERENCES MAIN_BOARD (BOARD_UID);
