CREATE TABLE MYPAGE
(
  -- 외래키 모음
  USER_UID        VARCHAR(100) NOT NULL COMMENT '사용자아이디',
  USER_NAME       VARCHAR(100) NOT NULL COMMENT '사용자이름',
  USER_GRADE      VARCHAR(100) NOT NULL COMMENT '사용자등급',
  POINT           INTEGER      NULL COMMENT '포인트',
  INQUIRY_UID     VARCHAR(100) NOT NULL COMMENT '1:1문의 UID',
  TRACKING_NUMBER VARCHAR(100) NOT NULL COMMENT '운송장번호'
  -- 외래키 INQUIRY_LIST에서 INQUIRY_UID
  -- 외래키 SHIPPING_RESERVATION에서 TRACKING_NUMBER 등 외래키
 
) COMMENT '마이페이지';
